Algoritmo "semnome"
// Disciplina  :  [Linguagem e Lógica de Programação] 
// Professor   : Antonio Carlos Nicolodi 
// Descrição   : Aqui você descreve o que o programa faz! (função)
// Autor(a)    : Nome do(a) aluno(a)
// Data atual  : 22-8-22
Var
x:inteiro
num:inteiro


Inicio
escreval("Escreva o número para o cálculo da tabuada")
leia(num)
x <- 1
repita
escreval(num," x ",num,":",x * num)
x <- x + 1

ate( x > 10)

Fimalgoritmo