Algoritmo "semnome"
// Disciplina  :  [Linguagem e Lógica de Programação] 
// Professor   : Antonio Carlos Nicolodi 
// Descrição   : Aqui você descreve o que o programa faz! (função)
// Autor(a)    : Nome do(a) aluno(a)
// Data atual  : 22-8-22
Var
x:real

Inicio
x <- 1
repita
se(x = 10)entao
escreval(x,": múltiplos de 10")
fimse

 se(x = 20)entao
escreval(":múltiplo de 10")
fimse



escreval(x)
x <- x + 1
ate(x > 20 )





Fimalgoritmo